version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: bachestic-db-sponsors
    restart: always
    environment:
      MYSQL_DATABASE: bachestic_db_sponsors
      MYSQL_ROOT_PASSWORD: root_password_seguro
    volumes:
      - bachestic_sponsors_db_data:/var/lib/mysql
    ports:
      - 3310:3306
    networks:
      - bachestic-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bachestic-sponsors-backend
    restart: always
    environment:
      - DATABASE_URL=mysql://root:root_password_seguro@db:3306/bachestic_db_sponsors
      - JWT_SECRET=bachestic_SaaS_2025_secure_key
      - PORT=3002
      - VITE_API_BASE=https://sponsors.bachestic.com
      - FRONTEND_URL=https://sponsors.bachestic.com
      - WOMPI_ENV=production

      # Wompi Bachestic
      - WOMPI_PUBLIC_KEY_BACHESTIC=pub_test_xxxxx
      - WOMPI_PRIVATE_KEY_BACHESTIC=prv_test_xxxxx
      - WOMPI_EVENTS_SECRET_BACHESTIC=evt_test_xxxxx
      - WOMPI_INTEGRITY_SECRET_BACHESTIC=test_integrity_xxxxx
      # Wompi Los Elite
      - WOMPI_PUBLIC_KEY_LOSELITE=pub_prod_9CwTKDgbcsQRfZF1ifFn9N5g7I6aNxSn
      - WOMPI_PRIVATE_KEY_LOSELITE=prv_prod_3fKzpxqEgb6tbxMde8oFWV466bOM3cXL
      - WOMPI_EVENTS_SECRET_LOSELITE=prod_events_8jcSbhorxaZ0BoYml2yUTFUCfHoDdyZD
      - WOMPI_INTEGRITY_SECRET_LOSELITE=prod_integrity_0gpwXOQYiqkhPRDl2DFFir9NLDPY0gZF
    ports:
      - "3020:3002"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bachestic-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: bachestic-sponsors-frontend
    restart: always
    ports:
      - "5180:5173"
    depends_on:
      - backend
    networks:
      - bachestic-net

networks:
  bachestic-net:
    driver: bridge

volumes:
  bachestic_sponsors_db_data: